name: testing
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  deployment:
    runs-on: ubuntu-latest # operating system your code will run on
    environment:
      name: testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt # install all our dependencies for the project
      - run: pytest . # run pytest test
